-- Sample Templates Data for SharpFlow AI Automation Marketplace
-- This file contains realistic template data across all categories

-- Using existing user profile as seller
-- User ID: b890b228-b08e-41b7-a4ba-5162055a5443

-- CHATBOTS CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'AI Customer Support Chatbot',
  'Intelligent chatbot that handles customer inquiries, FAQs, and support tickets with natural language processing. Integrates with popular helpdesk systems and can escalate complex issues to human agents.',
  (SELECT id FROM categories WHERE slug = 'chatbots'),
  49.99,
  FALSE,
  'templates/ai-customer-support-chatbot.json',
  ARRAY['previews/chatbot-customer-support.png', 'previews/chatbot-flow.png'],
  'Complete setup guide with step-by-step instructions for deploying an AI-powered customer support chatbot. Includes integration with Zendesk, Intercom, and custom APIs. Features sentiment analysis, automatic ticket routing, and multilingual support.',
  'https://youtube.com/watch?v=demo1',
  2847,
  4.8,
  156,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['customer-service', 'support', 'ai', 'nlp', 'zendesk', 'intercom']
),
(
  'Lead Qualification Chatbot',
  'Smart chatbot that engages website visitors, qualifies leads through intelligent questioning, and automatically routes high-quality prospects to your sales team.',
  (SELECT id FROM categories WHERE slug = 'chatbots'),
  39.99,
  FALSE,
  'templates/lead-qualification-chatbot.json',
  ARRAY['previews/lead-chatbot.png'],
  'Advanced lead qualification system with scoring algorithms, CRM integration, and automated follow-up sequences. Works with HubSpot, Salesforce, and Pipedrive.',
  'https://youtube.com/watch?v=demo2',
  1923,
  4.7,
  89,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['lead-generation', 'sales', 'qualification', 'crm', 'hubspot']
),
(
  'E-commerce Shopping Assistant',
  'AI-powered shopping assistant that helps customers find products, answers questions about inventory, and guides them through the purchase process.',
  (SELECT id FROM categories WHERE slug = 'chatbots'),
  0,
  TRUE,
  'templates/ecommerce-shopping-assistant.json',
  ARRAY['previews/shopping-assistant.png'],
  'Free template for e-commerce stores. Includes product recommendation engine, inventory checking, and order status updates. Compatible with Shopify, WooCommerce, and Magento.',
  NULL,
  5234,
  4.6,
  312,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['ecommerce', 'shopping', 'recommendations', 'shopify', 'free']
);

-- WORKFLOW AUTOMATION CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'Invoice Processing Automation',
  'Complete invoice processing workflow that extracts data from PDFs, validates information, and automatically enters data into your accounting system.',
  (SELECT id FROM categories WHERE slug = 'workflow-automation'),
  79.99,
  FALSE,
  'templates/invoice-processing-automation.json',
  ARRAY['previews/invoice-processing.png', 'previews/invoice-flow.png'],
  'Enterprise-grade invoice processing system with OCR capabilities, data validation, and integration with QuickBooks, Xero, and SAP. Includes error handling and manual review workflows.',
  'https://youtube.com/watch?v=demo3',
  1456,
  4.9,
  78,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['accounting', 'ocr', 'pdf', 'quickbooks', 'xero', 'enterprise']
),
(
  'Employee Onboarding Workflow',
  'Streamlined employee onboarding process that automates document collection, account creation, and training assignment across multiple systems.',
  (SELECT id FROM categories WHERE slug = 'workflow-automation'),
  59.99,
  FALSE,
  'templates/employee-onboarding-workflow.json',
  ARRAY['previews/onboarding-workflow.png'],
  'HR automation template that handles new hire paperwork, creates accounts in various systems, assigns training modules, and tracks completion. Integrates with BambooHR, Workday, and Slack.',
  'https://youtube.com/watch?v=demo4',
  892,
  4.7,
  45,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['hr', 'onboarding', 'bamboohr', 'workday', 'slack', 'training']
);

-- CONTENT GENERATION CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'AI Blog Content Generator',
  'Automated blog content creation system that generates SEO-optimized articles, schedules posts, and distributes content across multiple platforms.',
  (SELECT id FROM categories WHERE slug = 'content-generation'),
  69.99,
  FALSE,
  'templates/ai-blog-content-generator.json',
  ARRAY['previews/blog-generator.png', 'previews/content-calendar.png'],
  'Advanced content generation workflow using GPT-4 for article creation, SEO optimization, and multi-platform publishing. Includes content calendar management and performance tracking.',
  'https://youtube.com/watch?v=demo5',
  3421,
  4.8,
  198,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['content', 'blog', 'seo', 'gpt-4', 'wordpress', 'scheduling']
),
(
  'Social Media Content Planner',
  'AI-powered social media content creation and scheduling system that generates posts, hashtags, and optimal posting times across all major platforms.',
  (SELECT id FROM categories WHERE slug = 'content-generation'),
  0,
  TRUE,
  'templates/social-media-content-planner.json',
  ARRAY['previews/social-planner.png'],
  'Free social media automation template with AI content generation, hashtag research, and cross-platform scheduling. Works with Facebook, Instagram, Twitter, and LinkedIn.',
  'https://youtube.com/watch?v=demo6',
  7892,
  4.5,
  445,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['social-media', 'content', 'scheduling', 'hashtags', 'free', 'instagram']
);

-- DATA PROCESSING CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'Sales Data Analytics Dashboard',
  'Automated sales reporting system that collects data from multiple sources, processes it, and generates comprehensive dashboards and reports.',
  (SELECT id FROM categories WHERE slug = 'data-processing'),
  89.99,
  FALSE,
  'templates/sales-data-analytics-dashboard.json',
  ARRAY['previews/sales-dashboard.png', 'previews/analytics-charts.png'],
  'Enterprise sales analytics solution with real-time data processing, custom KPI tracking, and automated report generation. Integrates with Salesforce, HubSpot, and Google Analytics.',
  'https://youtube.com/watch?v=demo7',
  1234,
  4.9,
  67,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['analytics', 'sales', 'dashboard', 'kpi', 'salesforce', 'reporting']
);

-- EMAIL MARKETING CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'Abandoned Cart Recovery System',
  'Intelligent email sequence that automatically detects abandoned carts and sends personalized recovery emails with dynamic product recommendations.',
  (SELECT id FROM categories WHERE slug = 'email-marketing'),
  45.99,
  FALSE,
  'templates/abandoned-cart-recovery-system.json',
  ARRAY['previews/cart-recovery.png'],
  'E-commerce email automation with behavioral triggers, personalization, and A/B testing. Integrates with Shopify, WooCommerce, and major email platforms.',
  'https://youtube.com/watch?v=demo8',
  2156,
  4.7,
  124,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['ecommerce', 'email', 'cart-recovery', 'personalization', 'shopify']
),
(
  'Welcome Email Sequence',
  'Complete onboarding email series that nurtures new subscribers with valuable content and gradually introduces your products or services.',
  (SELECT id FROM categories WHERE slug = 'email-marketing'),
  0,
  TRUE,
  'templates/welcome-email-sequence.json',
  ARRAY['previews/welcome-sequence.png'],
  'Free email onboarding template with 7-email sequence, segmentation logic, and engagement tracking. Compatible with Mailchimp, ConvertKit, and ActiveCampaign.',
  NULL,
  6789,
  4.4,
  389,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['onboarding', 'email', 'sequence', 'nurturing', 'free', 'mailchimp']
);

-- LEAD GENERATION CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'LinkedIn Lead Generation Bot',
  'Automated LinkedIn outreach system that finds prospects, sends personalized connection requests, and follows up with targeted messages.',
  (SELECT id FROM categories WHERE slug = 'lead-generation'),
  99.99,
  FALSE,
  'templates/linkedin-lead-generation-bot.json',
  ARRAY['previews/linkedin-bot.png', 'previews/outreach-flow.png'],
  'Professional LinkedIn automation tool with smart targeting, personalized messaging, and CRM integration. Includes safety features to avoid account restrictions.',
  'https://youtube.com/watch?v=demo9',
  1678,
  4.6,
  92,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['linkedin', 'outreach', 'prospecting', 'b2b', 'sales', 'automation']
);

-- API INTEGRATIONS CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES 
(
  'Multi-Platform Inventory Sync',
  'Real-time inventory synchronization across multiple e-commerce platforms, marketplaces, and POS systems to prevent overselling.',
  (SELECT id FROM categories WHERE slug = 'api-integrations'),
  129.99,
  FALSE,
  'templates/multi-platform-inventory-sync.json',
  ARRAY['previews/inventory-sync.png'],
  'Enterprise inventory management solution with real-time sync, conflict resolution, and automated reordering. Supports Shopify, Amazon, eBay, and Square.',
  'https://youtube.com/watch?v=demo10',
  945,
  4.8,
  54,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['inventory', 'sync', 'ecommerce', 'amazon', 'shopify', 'pos']
),
(
  'Slack-to-Trello Integration',
  'Seamless integration that automatically creates Trello cards from Slack messages, assigns team members, and syncs updates between platforms.',
  (SELECT id FROM categories WHERE slug = 'api-integrations'),
  0,
  TRUE,
  'templates/slack-to-trello-integration.json',
  ARRAY['previews/slack-trello.png'],
  'Free productivity integration template that bridges communication and project management. Includes custom triggers, automated assignments, and status updates.',
  NULL,
  4567,
  4.5,
  267,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['slack', 'trello', 'productivity', 'project-management', 'free', 'team']
);

-- PRODUCTIVITY TOOLS CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES
(
  'Meeting Notes Automation',
  'AI-powered system that records meetings, generates transcripts, extracts action items, and distributes summaries to participants automatically.',
  (SELECT id FROM categories WHERE slug = 'productivity-tools'),
  59.99,
  FALSE,
  'templates/meeting-notes-automation.json',
  ARRAY['previews/meeting-notes.png', 'previews/transcript-flow.png'],
  'Advanced meeting automation with speech-to-text, AI summarization, and task extraction. Integrates with Zoom, Google Meet, and Microsoft Teams.',
  'https://youtube.com/watch?v=demo11',
  2345,
  4.7,
  134,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['meetings', 'transcription', 'ai', 'zoom', 'productivity', 'notes']
),
(
  'Expense Report Automation',
  'Smart expense tracking system that captures receipts, categorizes expenses, and generates reports for accounting and reimbursement.',
  (SELECT id FROM categories WHERE slug = 'productivity-tools'),
  39.99,
  FALSE,
  'templates/expense-report-automation.json',
  ARRAY['previews/expense-tracker.png'],
  'Complete expense management solution with OCR receipt scanning, automatic categorization, and integration with accounting software.',
  'https://youtube.com/watch?v=demo12',
  1789,
  4.6,
  98,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['expenses', 'receipts', 'ocr', 'accounting', 'reimbursement', 'finance']
);

-- CRM INTEGRATION CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES
(
  'Lead Scoring & Nurturing System',
  'Intelligent lead scoring algorithm that tracks prospect behavior, assigns scores, and triggers automated nurturing sequences based on engagement.',
  (SELECT id FROM categories WHERE slug = 'crm-integration'),
  79.99,
  FALSE,
  'templates/lead-scoring-nurturing-system.json',
  ARRAY['previews/lead-scoring.png', 'previews/nurturing-flow.png'],
  'Advanced CRM automation with behavioral tracking, predictive scoring, and multi-channel nurturing campaigns. Works with Salesforce, HubSpot, and Pipedrive.',
  'https://youtube.com/watch?v=demo13',
  1567,
  4.8,
  87,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['crm', 'lead-scoring', 'nurturing', 'salesforce', 'hubspot', 'automation']
),
(
  'Customer Lifecycle Management',
  'Complete customer journey automation from first contact to retention, including onboarding, upselling, and win-back campaigns.',
  (SELECT id FROM categories WHERE slug = 'crm-integration'),
  0,
  TRUE,
  'templates/customer-lifecycle-management.json',
  ARRAY['previews/lifecycle-management.png'],
  'Free CRM template for managing entire customer lifecycle with automated touchpoints, segmentation, and retention strategies.',
  NULL,
  3456,
  4.4,
  201,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['customer-lifecycle', 'retention', 'onboarding', 'upselling', 'free', 'crm']
);

-- SOCIAL MEDIA CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES
(
  'Instagram Growth Automation',
  'Comprehensive Instagram growth system with automated posting, engagement, hashtag research, and follower analysis.',
  (SELECT id FROM categories WHERE slug = 'social-media'),
  69.99,
  FALSE,
  'templates/instagram-growth-automation.json',
  ARRAY['previews/instagram-growth.png', 'previews/engagement-analytics.png'],
  'Professional Instagram marketing automation with content scheduling, engagement automation, and growth analytics. Includes compliance features.',
  'https://youtube.com/watch?v=demo14',
  2890,
  4.6,
  167,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['instagram', 'growth', 'engagement', 'hashtags', 'analytics', 'marketing']
),
(
  'Social Media Crisis Monitor',
  'Real-time social media monitoring system that detects negative mentions, alerts your team, and helps manage brand reputation crises.',
  (SELECT id FROM categories WHERE slug = 'social-media'),
  89.99,
  FALSE,
  'templates/social-media-crisis-monitor.json',
  ARRAY['previews/crisis-monitor.png'],
  'Enterprise social media monitoring with sentiment analysis, crisis detection, and automated response workflows. Covers all major platforms.',
  'https://youtube.com/watch?v=demo15',
  1123,
  4.7,
  64,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['monitoring', 'crisis-management', 'sentiment', 'reputation', 'alerts', 'enterprise']
);

-- E-COMMERCE CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES
(
  'Dynamic Pricing Optimizer',
  'AI-powered pricing system that automatically adjusts product prices based on competition, demand, inventory levels, and market conditions.',
  (SELECT id FROM categories WHERE slug = 'ecommerce'),
  149.99,
  FALSE,
  'templates/dynamic-pricing-optimizer.json',
  ARRAY['previews/pricing-optimizer.png', 'previews/price-analytics.png'],
  'Advanced e-commerce pricing automation with competitor monitoring, demand forecasting, and profit optimization algorithms.',
  'https://youtube.com/watch?v=demo16',
  876,
  4.9,
  43,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['pricing', 'optimization', 'competition', 'ai', 'profit', 'ecommerce']
),
(
  'Product Review Automation',
  'Automated system for collecting, managing, and responding to product reviews across multiple platforms and marketplaces.',
  (SELECT id FROM categories WHERE slug = 'ecommerce'),
  0,
  TRUE,
  'templates/product-review-automation.json',
  ARRAY['previews/review-automation.png'],
  'Free review management template with automated follow-ups, response templates, and review aggregation from multiple sources.',
  NULL,
  5678,
  4.3,
  324,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['reviews', 'feedback', 'automation', 'reputation', 'free', 'customer-service']
);

-- ANALYTICS & REPORTING CATEGORY TEMPLATES
INSERT INTO templates (
  title,
  description,
  category_id,
  price,
  is_free,
  file_url,
  preview_images,
  documentation,
  video_url,
  downloads_count,
  rating,
  rating_count,
  seller_id,
  is_featured,
  tags
) VALUES
(
  'Executive Dashboard Generator',
  'Automated executive reporting system that collects KPIs from multiple sources and generates beautiful, interactive dashboards.',
  (SELECT id FROM categories WHERE slug = 'analytics-reporting'),
  119.99,
  FALSE,
  'templates/executive-dashboard-generator.json',
  ARRAY['previews/executive-dashboard.png', 'previews/kpi-charts.png'],
  'Enterprise-grade reporting solution with real-time data aggregation, custom visualizations, and automated distribution to stakeholders.',
  'https://youtube.com/watch?v=demo17',
  1345,
  4.8,
  76,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  TRUE,
  ARRAY['dashboard', 'executive', 'kpi', 'reporting', 'analytics', 'enterprise']
),
(
  'Website Performance Monitor',
  'Comprehensive website monitoring system that tracks performance metrics, uptime, and user experience across multiple sites.',
  (SELECT id FROM categories WHERE slug = 'analytics-reporting'),
  49.99,
  FALSE,
  'templates/website-performance-monitor.json',
  ARRAY['previews/performance-monitor.png'],
  'Website monitoring automation with performance tracking, uptime alerts, and detailed reporting. Includes mobile and desktop testing.',
  'https://youtube.com/watch?v=demo18',
  2234,
  4.5,
  128,
  'b890b228-b08e-41b7-a4ba-5162055a5443',
  FALSE,
  ARRAY['monitoring', 'performance', 'uptime', 'website', 'alerts', 'seo']
);
